### ISSUE TITLE
It's not working on Manjaro

### ISSUE THREAD

**Issue by MasterCruelty** [MasterCruelty/eMerger#50]
If you launch the setup on Manjaro you would see this error:

```/src/utils/global.sh is missing```
Also it doesnt find ```.cache``` returning another error:
```cat: /home/user/Updater/src/utils/.cache: No such file or directory```

**Comment by MasterCruelty** [comment]
@archetipico Maybe you know what is causing this problem 
❓ ❔

**Comment by archetipico** [comment]
It's not Manjaro-only, it's a `setup.sh` problem.
I'm working on it.

**Comment by archetipico** [comment]
Found the bug: `setup.sh` is run, then it runs `integrity_check.sh` but `integrity_check.sh` checks for `.cache` existence, but if it's the first installation ever, that file doesn't exist. I'll PR a solution soon.
