### ISSUE TITLE
Improve error tracking

### ISSUE THREAD

**Issue by MasterCruelty** [MasterCruelty/eMerger#60]
We should delete ```.errors``` when we launch ```.fetch.sh```.
Also when launching ```up``` we should check if ```.errors``` exists not empty and say something about it to the user.

**Comment by archetipico** [comment]
Since I was planning to create a better error-tracking system (tracking even errors in other files), what if an error occurs during `fetch.sh`? Since in #64 I talk about automatic updating at startup, what if we delete the error log at startup, BEFORE running `fetch.sh`?

**Comment by MasterCruelty** [comment]
> Since I was planning to create a better error-tracking system (tracking even errors in other files), what if an error occurs during `fetch.sh`? Since in #64 I talk about automatic updating at startup, what if we delete the error log at startup, BEFORE running `fetch.sh`?

It's a good idea. But if you forgot to read the error and you turn off your device, then when you reboot you can't read it anymore because ```fetch.sh``` is already executed and it deleted the error file.

**Comment by MasterCruelty** [comment]
@archetipico so the first half of this issue is solved.
We still have to delete .errors during startup before ```update.sh``` executes.

Do we Need this remove only in case of a installed cronjob or every time se execute ```update.sh```?

**Comment by archetipico** [comment]
We need it everytime since we will track errors on other files too

**Comment by MasterCruelty** [comment]
> We need it everytime since we will track errors on other files too

Yes but as you said a few days ago, what if an error occurs during ```update.sh```.
When .errors will be automatically cleaned to avoid a large file that can keep growing???

**Comment by archetipico** [comment]
We can create separators inside `.errors`, if the file reaches (for example) 1000+ lines, it clears errors separator by separator, till it gets shorter than (for example again) 1000 lines

**Comment by MasterCruelty** [comment]
> We can create separators inside `.errors`, if the file reaches (for example) 1000+ lines, it clears errors separator by separator, till it gets shorter than (for example again) 1000 lines

It could work
