### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by archetipico** [MasterCruelty/eMerger#63]
We need a personalized ASCII logo (maybe we can create it on-the-go depending on the screen size) and we need an actual art logo (using GIMP?).

**Comment by MasterCruelty** [comment]
> We need a personalized ASCII logo (maybe we can create it on-the-go depending on the screen size) and we need an actual art logo (using GIMP?).

I'm not expert at drawwing....
maybe @NespoliBT ??
