### ISSUE TITLE
Annoying message

### ISSUE THREAD

**Issue by archetipico** [MasterCruelty/eMerger#66]
Annoying `warning: redirecting to https://github.com/MasterCruelty/eMerger.git/` when running `fetch.sh`. How (if possible) should we get rid of it?

**Comment by MasterCruelty** [comment]
I think you can fix by deleting and cloning again the repository

**Comment by archetipico** [comment]
That doesn't fix the issue and I don't know if it's me only (I both have my clone and your remote)

**Comment by MasterCruelty** [comment]
> That doesn't fix the issue and I don't know if it's me only (I both have my clone and your remote)

I'll try some tests in the next days.
I had this error on Fedora only.
There isn't on Raspberry pi

**Comment by MasterCruelty** [comment]
@archetipico I'm wondering if it's because of something we did recently such as the change of the repository name but i'm not sure.

**Comment by MasterCruelty** [comment]
@archetipico ok now I get the message on Raspberry Pi too. So I think the problem is related to the use of ```fetch.sh```

**Comment by archetipico** [comment]
I looked for hints online, I've found nothing useful because no solution works for me.

**Comment by archetipico** [comment]
Oh well I've just solved it

**Comment by MasterCruelty** [comment]
> Oh well I've just solved it

How?
