### ISSUE TITLE
[1.0] Improve content

### ISSUE THREAD

**Issue by archetipico** [MasterCruelty/eMerger#71]
File size and number is growing. We need to keep track of what every file does and where. I suggest using more comments and maybe creating a UML chart.

**Comment by MasterCruelty** [comment]
> File size and number is growing. We need to keep track of what every file does and where. I suggest using more comments and maybe creating a UML chart.

It was on my plan to do, it is starting to be a little bit difficult to follow the flow

**Comment by MasterCruelty** [comment]
@archetipico what if we write the documentation in LaTeX?

**Comment by archetipico** [comment]
Do this pls

**Comment by MasterCruelty** [comment]
> Do this pls

🆗
