### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by archetipico** [MasterCruelty/eMerger#78]
Path error in `emerger.sh`. We are looking for `cat .errors` but no path is specified.

**Comment by archetipico** [comment]
I'm fixing this

**Comment by MasterCruelty** [comment]
> I'm fixing this
> 

Isn't It working? It was until now

**Comment by archetipico** [comment]
It worked, but only if you were inside `eMerger` directory, otherwise `-s` would just tell you that `.errors` was clear... since it actually didn't exist.

**Comment by MasterCruelty** [comment]
> It worked, but only if you were inside `eMerger` directory, otherwise `-s` would just tell you that `.errors` was clear... since it actually didn't exist.

Got it
