### ISSUE TITLE
Autoupdate not working [REMOVING FEATURE]

### ISSUE THREAD

**Issue by archetipico** [MasterCruelty/eMerger#84]
I'm on Debian and `up -au` is not working. Probably permissions problems since `crontab -e` returns a positive feedback (it contains the right string). I know it's now working since it didn't auto-update using our last commit and `.log` contained timestamps two days old (=> it didn't update today when I started up my PC)

**Comment by archetipico** [comment]
I just did a new Debian XFCE installation on another machine. The problem persists.
We should anyway move to `systemd` since `crontab` is deprecated, though I tried to implement `systemd` on another script of mine and it didn't work either (it is shown as `running` and `enabled` but it doesn't work, so probably it's XFCE and not Debian?)

**Comment by archetipico** [comment]
I'm thinking of removing the auto-update since I'm not willing to maintain it and I don't even find it necessary anymore. I think it's better if the user chooses if and how to set automation, I don't want to force a cronjob and bloat this script with possibly useless features... even if you auto-update you still have to interact with the script (to type y/n or for your password), so I don't see the utility and I can't understand how approx. 100 lines of code (if not more because I don't know how every *nix system works) and start-up delay are better than opening a terminal and typing `up`.

**Comment by archetipico** [comment]
I'm going to leave the issue open but I'll close it whenever I can actually fix it... or if someone comes out with a one-line solution to the problem :)

**Comment by archetipico** [comment]
Is there something like a poll on GitHub?
I propose to remove this feature... not only it does not always work, but I don't even think it's something someone would use daily: I want to watch my console when I type these kind of scripts, I don't trust myself enough ahahah

**Comment by MasterCruelty** [comment]
> Is there something like a poll on GitHub? I propose to remove this feature... not only it does not always work, but I don't even think it's something someone would use daily: I want to watch my console when I type these kind of scripts, I don't trust myself enough ahahah

Honestly I never used this feature, I think we can remove it but I don't know if someone liked it and currently using it.

**Comment by archetipico** [comment]
I don't think more than 10-20 people know about this repository, I think we can proceed with the remove option.
