### ISSUE TITLE
:x: -nt option isn't working

### ISSUE THREAD

**Issue by MasterCruelty** [MasterCruelty/eMerger#92]
If I type <code>up -nt</code> eMerger still does the clean process after the update

**Comment by archetipico** [comment]
Sorry I didn't use GitHub for a while, I can't test right now but is `utils/trash` inside your auto-generated cache? If not, try to re-generate with `up -rc`. The affected code is:

```
if [[ $LINE == "utils/trash" && $ARGV =~ "-nt" ]]; then
    continue
fi
```

**Comment by MasterCruelty** [comment]
> 

I try and I let you know

**Comment by MasterCruelty** [comment]
> Sorry I didn't use GitHub for a while, I can't test right now but is `utils/trash` inside your auto-generated cache? If not, try to re-generate with `up -rc`. The affected code is:
> 
> ```
> if [[ $LINE == "utils/trash" && $ARGV =~ "-nt" ]]; then
>     continue
> fi
> ```

It doesn't work your solution :/

**Comment by archetipico** [comment]
Again as the other issue, `-nt` works on my machine and the code makes sense too...

**Comment by MasterCruelty** [comment]
> Again as the other issue, `-nt` works on my machine and the code makes sense too...

Now I could reproduce and it seems working. I close this too
