### ISSUE TITLE
:printer: weird print with -err option 

### ISSUE THREAD

**Issue by MasterCruelty** [MasterCruelty/eMerger#93]
If I type <code>up -err</code> and there is no errors, eMerger prints twice "No errors found"

**Comment by archetipico** [comment]
Line 33 of `emerger.sh`

```
elif [[ $ARGV =~ "-err" ]]; then
    if [[ *finds error* ]]; then
        puts RED "Errors found\nOpen .log in $ROOT to see what's wrong"
    else
        puts GREEN "No errors found"
    fi
```

It's intended!

**Comment by archetipico** [comment]
I didn't read "twice"

**Comment by MasterCruelty** [comment]
> Line 33 of `emerger.sh`
> 
> ```
> elif [[ $ARGV =~ "-err" ]]; then
>     if [[ *finds error* ]]; then
>         puts RED "Errors found\nOpen .log in $ROOT to see what's wrong"
>     else
>         puts GREEN "No errors found"
>     fi
> ```
> 
> It's intended!



> I didn't read "twice"

I see

**Comment by MasterCruelty** [comment]
> I can't reproduce this issue... I guess it works on my machine!

At the moment it works on my machine too. I don't know why it occured this thing

**Comment by archetipico** [comment]
Perfect, we can't see the bug, the bug is not there!
